---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "This project contains the shared OpenLDAP deployment"
    openshift.io/display-name: "OpenLDAP"
  name: openldap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: openldap
  labels:
    app.kubernetes.io/name: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
    spec:
      serviceAccountName: openldap-sa
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_USERNAME
                  name: server-credentials
            - name: LDAP_ROOT
              value: "dc=acme,dc=org"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_PASSWORD
                  name: server-credentials
            - name: LDAP_CUSTOM_LDIF_DIR
              value: /tmp/ldifs
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
            - name: ldifs-volume
              mountPath: /tmp/ldifs
      volumes:
        - name: ldifs-volume
          configMap:
            name: server-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: openldap
  labels:
    app.kubernetes.io/name: server
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: server
---
apiVersion: v1
kind: Secret
metadata:
  name: server-credentials
  namespace: openldap
type: Opaque
stringData:
  LDAP_ADMIN_USERNAME: admin
  LDAP_ADMIN_PASSWORD: adminpassword
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap-sa
  namespace: openldap
---
# Role for openldap-sa
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-anyuid-scc
  namespace: openldap
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
---
# Rolebinding for openldap-sa, check the sa namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openldap-sa-allow-anyuid-scc
  namespace: openldap
subjects:
  - kind: ServiceAccount
    name: openldap-sa
    namespace: openldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-anyuid-scc

---
# ConfigMap with all ldifs
kind: ConfigMap
apiVersion: v1
metadata:
  name: server-configuration
  namespace: openldap
data:
  00-organization.ldif: |
    dn: dc=acme,dc=org
    objectClass: top
    objectClass: domain
    description: This organization contains users that can be used to test configuration of other products.

    dn: ou=people,dc=acme,dc=org
    objectClass: organizationalUnit
    description: People in Acme's organization

    dn: ou=groups,dc=acme,dc=org
    objectClass: organizationalUnit
    description: Groups in Acme's organization to group people

  10-users.ldif: |
    dn: uid=user-01,ou=people,dc=acme,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: One
    sn: One
    displayName: User 01
    mail: user-01@acme.org
    userPassword: password
    uid: user-01

    dn: uid=user-02,ou=people,dc=acme,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Two
    sn: Two
    displayName: User 02
    mail: user-02@acme.org
    userPassword: password
    uid: user-02

    dn: uid=user-11,ou=people,dc=acme,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Eleven
    sn: Eleven
    displayName: User 11
    mail: user-11@acme.org
    userPassword: password
    uid: user-11

    dn: uid=user-12,ou=people,dc=acme,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Twelve
    sn: Twelve
    displayName: User 12
    mail: user-12@acme.org
    userPassword: password
    uid: user-12
    
  20-groups.ldif: |
    dn: cn=admin,ou=groups,dc=acme,dc=org
    cn: admin
    objectclass: groupOfNames
    member: uid=user-01,ou=people,dc=acme,dc=org
    member: uid=user-02,ou=people,dc=acme,dc=org

    dn: cn=viewer,ou=groups,dc=acme,dc=org
    cn: viewer
    objectclass: groupOfNames
    member: uid=user-11,ou=people,dc=acme,dc=org
    member: uid=user-12,ou=people,dc=acme,dc=org
