---
kind: LDAPSyncConfig
apiVersion: v1
# Connection Details
url: ldap://localhost:1389
bindDN: CN=admin,DC=acme,DC=org
bindPassword: adminpassword
insecure: true 
# ca: my-ldap-ca-bundle.crt
# [Optional] Groups mapping
groupUIDNameMapping:
  "cn=admin,ou=groups,dc=acme,dc=org": ldap-admins
  "cn=viewer,ou=groups,dc=acme,dc=org": ldap-viewers
# LDAP sync configuration
rfc2307:
  groupsQuery:
    baseDN: "ou=groups,dc=acme,dc=org"
    scope: sub
    derefAliases: never
    filter: (objectClass=groupOfNames)
    pageSize: 0
  groupUIDAttribute: dn 
  groupNameAttributes: [ cn ] 
  groupMembershipAttributes: [ member ]
  usersQuery:
    baseDN: "ou=people,dc=acme,dc=org"
    scope: sub
    derefAliases: never
    pageSize: 0
  userUIDAttribute: dn 
  userNameAttributes: [ uid ]
  tolerateMemberNotFoundErrors: false
  tolerateMemberOutOfScopeErrors: false
...
