---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "This project contains jobs that sync the LDAP groups with OCP"
    openshift.io/display-name: "LDAP Sync"
  name: ldap-sync
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
  - apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
    verbs:
      - get
      - list
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-group-syncer
subjects:
  - kind: ServiceAccount
    name: ldap-group-syncer              
    namespace: ldap-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-group-syncer
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: ldap-sync
stringData:
  bindPassword: adminpassword
type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    # Connection Details
    url: ldap://server.openldap.svc:1389
    bindDN: CN=admin,DC=acme,DC=org
    bindPassword:
      file: "/etc/secrets/bindPassword"
    insecure: true 
    # ca: my-ldap-ca-bundle.crt
    # [Optional] Groups mapping
    groupUIDNameMapping:
      "cn=admin,ou=groups,dc=acme,dc=org": ldap-admins
      "cn=viewer,ou=groups,dc=acme,dc=org": ldap-viewers
    # LDAP sync configuration
    rfc2307:
      groupsQuery:
        baseDN: "ou=groups,dc=acme,dc=org"
        scope: sub
        derefAliases: never
        filter: (objectClass=groupOfNames)
        pageSize: 0
      groupUIDAttribute: dn 
      groupNameAttributes: [ cn ] 
      groupMembershipAttributes: [ member ]
      usersQuery:
        baseDN: "ou=people,dc=acme,dc=org"
        scope: sub
        derefAliases: never
        pageSize: 0
      userUIDAttribute: dn 
      userNameAttributes: [ uid ]
      tolerateMemberNotFoundErrors: false
      tolerateMemberOutOfScopeErrors: false
  whitelist.txt: |
    cn=testgroup01,ou=groups,dc=acme,dc=org
    cn=testgroup02,ou=groups,dc=acme,dc=org
    # cn=testgroup03,ou=groups,dc=acme,dc=org
  blacklist.txt: |
    cn=testgroup02,ou=groups,dc=acme,dc=org

---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
spec:                          
  # ┌───────────── minute (0–59)
  # │ ┌───────────── hour (0–23)
  # │ │ ┌───────────── day of the month (1–31)
  # │ │ │ ┌───────────── month (1–12)
  # │ │ │ │ ┌───────────── day of the week (0–6) (Sunday to Saturday;
  # │ │ │ │ │                                   7 is also Sunday on some systems)
  # │ │ │ │ │
  # │ │ │ │ │                                                      
  schedule: "*/30 * * * *"                                                           
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: cronjob-ldap-group-sync
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800                                                  
      template:
        metadata:
          labels:
            app: cronjob-ldap-group-sync
        spec:
          containers:
            - name: ldap-group-sync
              image: "registry.redhat.io/openshift4/ose-cli:v4.12"
              command:
                - "/bin/bash"
                - "-c"
                - "oc adm groups sync \
                  --whitelist=/etc/config/whitelist.txt \
                  --sync-config=/etc/config/sync.yaml --confirm"
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                  - ALL
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
                # - mountPath: "/etc/ldap-ca"
                #   name: "ldap-ca"
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-group-syncer"
            - name: "ldap-bind-password"
              secret:
                secretName: "ldap-secret"                                            
            # - name: "ldap-ca"
            #   configMap:
            #     name: "ca-config-map"                                                
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"